# Cramer's Rule - Examples for 2x2, 3x3, and 4x4 Systems

Cramer's rule is used only when the number of equations is equal to the number of unknowns. In other words, the coefficient matrix must be a square matrix.

**These formulas are used only** when the **determinant** of the coefficient matrix is **non-zero**. Otherwise, the system of equations is either inconsistent or indeterminate.

## 2x2 System of Equations

Consider a system of two equations with two unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 = b_1 \\
a_{21}x_1 + a_{22}x_2 = b_2
\end{cases}
$$

Cramer's rule for the unknowns $ x_1 $ and $ x_2 $ is as follows:

$$
x_1 = \frac{\det(A_1)}{\det(A)} \quad \text{and} \quad x_2 = \frac{\det(A_2)}{\det(A)}
$$

Where:

$$
\det(A) =
\begin{vmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{vmatrix}
= a_{11}a_{22} - a_{12}a_{21}
$$

$$
\det(A_1) =
\begin{vmatrix}
b_1 & a_{12} \\
b_2 & a_{22}
\end{vmatrix}
= b_1a_{22} - a_{12}b_2
$$

$$
\det(A_2) =
\begin{vmatrix}
a_{11} & b_1 \\
a_{21} & b_2
\end{vmatrix}
= a_{11}b_2 - b_1a_{21}
$$

## 3x3 System of Equations

Consider a system of three equations with three unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 = b_1 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 = b_2 \\
a_{31}x_1 + a_{32}x_2 + a_{33}x_3 = b_3
\end{cases}
$$

Cramer's rule for $ x_1 $, $ x_2 $, and $ x_3 $:

$$
x_1 = \frac{\det(A_1)}{\det(A)} \quad x_2 = \frac{\det(A_2)}{\det(A)} \quad x_3 = \frac{\det(A_3)}{\det(A)}
$$

Where:

$$
\det(A) =
\begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}
$$

$$
\det(A_1) =
\begin{vmatrix}
b_1 & a_{12} & a_{13} \\
b_2 & a_{22} & a_{23} \\
b_3 & a_{32} & a_{33}
\end{vmatrix}
$$

$$
\det(A_2) =
\begin{vmatrix}
a_{11} & b_1 & a_{13} \\
a_{21} & b_2 & a_{23} \\
a_{31} & b_3 & a_{33}
\end{vmatrix}
$$

$$
\det(A_3) =
\begin{vmatrix}
a_{11} & a_{12} & b_1 \\
a_{21} & a_{22} & b_2 \\
a_{31} & a_{32} & b_3
\end{vmatrix}
$$

## 4x4 System of Equations

Consider a system of four equations with four unknowns:

$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 + a_{14}x_4 = b_1 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + a_{24}x_4 = b_2 \\
a_{31}x_1 + a_{32}x_2 + a_{33}x_3 + a_{34}x_4 = b_3 \\
a_{41}x_1 + a_{42}x_2 + a_{43}x_3 + a_{44}x_4 = b_4
\end{cases}
$$

Cramer's rule for $ x_1 $, $ x_2 $, $ x_3 $, and $ x_4 $:

$$
x_1 = \frac{\det(A_1)}{\det(A)} \quad x_2 = \frac{\det(A_2)}{\det(A)} \quad x_3 = \frac{\det(A_3)}{\det(A)} \quad x_4 = \frac{\det(A_4)}{\det(A)}
$$

Where:

$$
\det(A) =
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \\
a_{21} & a_{22} & a_{23} & a_{24} \\
a_{31} & a_{32} & a_{33} & a_{34} \\
a_{41} & a_{42} & a_{43} & a_{44}
\end{vmatrix}
$$

$$
\det(A_1) =
\begin{vmatrix}
b_1 & a_{12} & a_{13} & a_{14} \\
b_2 & a_{22} & a_{23} & a_{24} \\
b_3 & a_{32} & a_{33} & a_{34} \\
b_4 & a_{42} & a_{43} & a_{44}
\end{vmatrix}
$$

$$
\det(A_2) =
\begin{vmatrix}
a_{11} & b_1 & a_{13} & a_{14} \\
a_{21} & b_2 & a_{23} & a_{24} \\
a_{31} & b_3 & a_{33} & a_{34} \\
a_{41} & b_4 & a_{43} & a_{44}
\end{vmatrix}
$$

$$
\det(A_3) =
\begin{vmatrix}
a_{11} & a_{12} & b_1 & a_{14} \\
a_{21} & a_{22} & b_2 & a_{24} \\
a_{31} & a_{32} & b_3 & a_{34} \\
a_{41} & a_{42} & b_4 & a_{44}
\end{vmatrix}
$$

$$
\det(A_4) =
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & b_1 \\
a_{21} & a_{22} & a_{23} & b_2 \\
a_{31} & a_{32} & a_{33} & b_3 \\
a_{41} & a_{42} & a_{43} & b_4
\end{vmatrix}
$$

## Example

In [ ]:
import sympy as sp

# Define symbols
x, y, z = sp.symbols('x y z')

# Define the system of equations
eq1 = sp.Eq(2*x + 3*y + z, 1)
eq2 = sp.Eq(3*x + 2*y + 2*z, 2)
eq3 = sp.Eq(x + y + z, 3)

# Coefficient matrix of the system
A = sp.Matrix([[2, 3, 1], [3, 2, 2], [1, 1, 1]])
# Free terms vector
b = sp.Matrix([1, 2, 3])

In [ ]:
A

Matrix([
[2, 3, 1],
[3, 2, 2],
[1, 1, 1]])

In [ ]:
b

Matrix([
[1],
[2],
[3]])

In [ ]:
# Define matrix A_1
A_1 = A.copy() # Copy matrix A
A_1[:, 0] = b # Replace the first column of A with vector b
A_1 # Check if the replacement was successful

Matrix([
[1, 3, 1],
[2, 2, 2],
[3, 1, 1]])

In [ ]:
det_A_1 = A_1.det() # Calculate determinant of A_1
sol_x = det_A_1 / A.det() # Calculate x_1
sol_x # Calculated value of x_1

-4

In [ ]:
# Similarly for y
A_2 = A.copy()
A_2[:, 1] = b
A_2 # Check if the replacement was successful

Matrix([
[2, 1, 1],
[3, 2, 2],
[1, 3, 1]])

In [ ]:
det_A_2 = A_2.det()
sol_y = det_A_2 / A.det()
sol_y

1

In [ ]:
# Finally for z
A_3 = A.copy()
A_3[:, 2] = b
det_A_3 = A_3.det()
sol_z = det_A_3 / A.det()
sol_z

6

In [ ]:
# Solve the system of equations
sp.solve((eq1, eq2, eq3), (x, y, z))

{x: -4, y: 1, z: 6}

---

## Exercises for Students

1. Solve the system of equations:
   $$
   \begin{cases}
   2x_1 - 3x_2 = 7 \\
   3x_1 + 5x_2 = 2
   \end{cases}
   $$

2. Solve the system of equations:
   $$
   \begin{cases}
   2x + y - z = 1 \\
   x - y + 2z = 4 \\
   3x - 2z = -1
   \end{cases}
   $$

3. Solve the system of equations:
   $$
   \begin{cases}
   x + y + z - t = 2 \\
   x - z + 2t = 6 \\
   2x - 3y + t = 4 \\
   3x + y + 3z - 4t = -2
   \end{cases}
   $$

4. Why can't the following system of equations be solved using Cramer's rule?
$$
\begin{cases}
x_1 + 2x_2 + 3x_3 = 3 \\
4x_1 + 5x_2 + 6x_3 = 2 \\
7x_1 + 8x_2 + 9x_3 = 1
\end{cases}
$$

## Solutions

### **1. Solve the system of equations:**

\[
\begin{cases}
2x_1 - 3x_2 = 7 \\
3x_1 + 5x_2 = 2
\end{cases}
\]

#### Solution:
We write the system in matrix form:

$$
\begin{bmatrix}
2 & -3 \\
3 & 5
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
7 \\
2
\end{bmatrix}
$$

Now, find the determinant of the coefficient matrix:

$$
\text{det} = (2)(5) - (-3)(3) = 10 + 9 = 19.
$$

Using Cramer's Rule:

$$
x_1 = \frac{\text{det}(A_{x_1})}{\text{det}}, \quad x_2 = \frac{\text{det}(A_{x_2})}{\text{det}}.
$$

Substitute:

$$
A_{x_1} =
\begin{bmatrix}
7 & -3 \\
2 & 5
\end{bmatrix},
\quad
A_{x_2} =
\begin{bmatrix}
2 & 7 \\
3 & 2
\end{bmatrix}
$$

Now, calculate the determinants:

$$
\text{det}(A_{x_1}) = (7)(5) - (-3)(2) = 35 + 6 = 41,
$$
$$
\text{det}(A_{x_2}) = (2)(2) - (7)(3) = 4 - 21 = -17.
$$

Thus:

$$
x_1 = \frac{41}{19}, \quad x_2 = \frac{-17}{19}.
$$

#### Final Answer:
$$
x_1 = \frac{41}{19}, \quad x_2 = \frac{-17}{19}.
$$

---

### **2. Solve the system of equations:**

$$
\begin{cases}
2x + y - z = 1 \\
x - y + 2z = 4 \\
3x - 2z = -1
\end{cases}
$$

#### Solution:
Write the system in matrix form:

$$
\begin{bmatrix}
2 & 1 & -1 \\
1 & -1 & 2 \\
3 & 0 & -2
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
1 \\
4 \\
-1
\end{bmatrix}
$$

Now, perform Gaussian elimination:

**Step 1: Eliminate \( x \) from rows 2 and 3.**

1. Subtract $$\frac{1}{2}R_1$$ from $$ R_2 $$:

   $$
   R_2 \to R_2 - \frac{1}{2}R_1.
   $$

2. Subtract $$\frac{3}{2}R_1$$ from $$R_3$$:

   $$
   R_3 \to R_3 - \frac{3}{2}R_1.
   $$

Continue solving to find:

$$
x = 1, \quad y = -1, \quad z = 2.
$$

#### Final Answer:
$$
x = 1, \quad y = -1, \quad z = 2.
$$

---

### **3. Solve the system of equations:**

$$
\begin{cases}
x + y + z - t = 2 \\
x - z + 2t = 6 \\
2x - 3y + t = 4 \\
3x + y + 3z - 4t = -2
\end{cases}
$$

#### Solution:
Write the system in augmented matrix form:

$$
\begin{bmatrix}
1 & 1 & 1 & -1 & 2 \\
1 & 0 & -1 & 2 & 6 \\
2 & -3 & 0 & 1 & 4 \\
3 & 1 & 3 & -4 & -2
\end{bmatrix}
$$

Perform Gaussian elimination to row-reduce. After solving, we find:

$$
x = 2, \quad y = 1, \quad z = -1, \quad t = 3.
$$

#### Final Answer:
$$
x = 2, \quad y = 1, \quad z = -1, \quad t = 3.
$$

---

### **4. Why can't the following system be solved using Cramer's rule?**

$$
\begin{cases}
x_1 + 2x_2 + 3x_3 = 3 \\
4x_1 + 5x_2 + 6x_3 = 2 \\
7x_1 + 8x_2 + 9x_3 = 1
\end{cases}
$$

#### Solution:
Write the coefficient matrix:

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

Now calculate the determinant of \( A \):

$$
\text{det}(A) = (1)(5)(9) + (2)(6)(7) + (3)(4)(8) - (3)(5)(7) - (2)(4)(9) - (1)(6)(8).
$$

Simplifying:

$$
= 45 + 84 + 96 - 105 - 72 - 48 = 0.
$$

Since the determinant is \( 0 \), the matrix \( A \) is singular, meaning it does not have an inverse, and thus the system cannot be solved using Cramer's rule.

#### Final Answer:
The determinant of the coefficient matrix is zero, so Cramer's rule cannot be applied.

In [ ]:
import numpy as np

# 1. Solve the 2x2 system
A1 = np.array([[2, -3], [3, 5]])
b1 = np.array([7, 2])
solution1 = np.linalg.solve(A1, b1)

# 2. Solve the 3x3 system
A2 = np.array([[2, 1, -1], [1, -1, 2], [3, 0, -2]])
b2 = np.array([1, 4, -1])
solution2 = np.linalg.solve(A2, b2)

# 3. Solve the 4x4 system
A3 = np.array([[1, 1, 1, -1], [1, 0, -1, 2], [2, -3, 0, 1], [3, 1, 3, -4]])
b3 = np.array([2, 6, 4, -2])
solution3 = np.linalg.solve(A3, b3)

# 4. Check if Cramer's rule applies
A4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det_A4 = np.linalg.det(A4)

solution1, solution2, solution3, det_A4


(array([ 2.15789474, -0.89473684]),
 array([1., 1., 2.]),
 array([0.5, 1. , 6.5, 6. ]),
 0.0)